# Generated by Django 3.1.1 on 2020-11-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201112_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='writer',
            field=models.EmailField(max_length=30, verbose_name='WRITER'),
        ),
    ]
