# Generated by Django 3.0.2 on 2020-04-09 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='TITLE')),
                ('description', models.CharField(blank=True, max_length=100)),
                ('place', models.CharField(max_length=100, verbose_name='PLACE')),
                ('url', models.URLField(verbose_name='URL')),
                ('start_dt', models.DateTimeField(verbose_name='Start Date')),
                ('end_dt', models.DateTimeField(verbose_name='End Date')),
                ('upload_dt', models.DateTimeField(auto_now_add=True, verbose_name='Upload Date')),
            ],
            options={
                'ordering': ('-upload_dt',),
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='레벨에 대한 설명')),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='academy/%Y/%m')),
                ('contents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.Contents')),
            ],
        ),
        migrations.AddField(
            model_name='contents',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.Level'),
        ),
    ]
